// Generated by scripts/gen-command-reference.mjs. Do not edit manually.
// Regenerate via `npm run command-reference`.
export const PUBLIC_COMMAND_ENTRIES = [
  {
    id: "help",
    title: "Gittensory command help",
    description: "Show public-safe @gittensory command help.",
  },
  {
    id: "ask",
    title: "Gittensory contribution context Q&A",
    description:
      "Answer contribution-quality questions from connected cached sources with citations.",
  },
  {
    id: "preflight",
    title: "Gittensory preflight",
    description: "Summarize public PR hygiene and validation readiness.",
  },
  {
    id: "blockers",
    title: "Gittensory readiness blockers",
    description: "Explain public-safe readiness blockers.",
  },
  {
    id: "duplicate-check",
    title: "Gittensory duplicate & WIP check",
    description: "Summarize duplicate and in-progress overlap caution.",
  },
  {
    id: "miner-context",
    title: "Gittensory miner context",
    description: "Confirm public Gittensor miner context when available.",
  },
  {
    id: "next-action",
    title: "Gittensory next step",
    description: "Suggest the next public-safe action.",
  },
  {
    id: "reviewability",
    title: "Gittensory PR readiness",
    description: "Summarize maintainer-friendly PR readiness without private review internals.",
  },
  {
    id: "repo-fit",
    title: "Gittensory repository fit",
    description: "Summarize public-safe repository fit signals.",
  },
  {
    id: "packet",
    title: "Gittensory public packet",
    description: "Prepare public-safe PR packet guidance.",
  },
] as const;

export const PUBLIC_COMMAND_LIST =
  "@gittensory help\n@gittensory ask\n@gittensory preflight\n@gittensory blockers\n@gittensory duplicate-check\n@gittensory miner-context\n@gittensory next-action\n@gittensory reviewability\n@gittensory repo-fit\n@gittensory packet";

export const MAINTAINER_COMMAND_ENTRIES = [
  {
    id: "queue-summary",
    title: "Gittensory maintainer queue summary",
    description: "Post a maintainer-only queue digest from cached GitHub metadata.",
  },
  {
    id: "confirmed-miners",
    title: "Gittensory confirmed-miner PRs",
    description: "List open PRs whose authors are confirmed in the official-miner cache.",
  },
  {
    id: "review-now",
    title: "Gittensory review-now queue",
    description: "List cached PRs that look ready for maintainer review.",
  },
  {
    id: "needs-author",
    title: "Gittensory needs-author queue",
    description: "List cached PRs that need author cleanup before detailed review.",
  },
  {
    id: "duplicate-clusters",
    title: "Gittensory duplicate clusters",
    description: "List duplicate or WIP clusters visible from cached GitHub metadata.",
  },
  {
    id: "burden-forecast",
    title: "Gittensory burden forecast",
    description: "Project maintainer review load and queue-growth risk from cached metadata.",
  },
  {
    id: "intake-health",
    title: "Gittensory intake health",
    description: "Summarize contributor-intake health from cached queue and config signals.",
  },
  {
    id: "outcome-patterns",
    title: "Gittensory outcome patterns",
    description: "Summarize what this repo actually merges vs closes from cached PR outcomes.",
  },
  {
    id: "noise-report",
    title: "Gittensory noise report",
    description: "Highlight queue noise sources maintainers should triage first.",
  },
] as const;

export const MAINTAINER_COMMAND_LIST =
  "@gittensory queue-summary\n@gittensory confirmed-miners\n@gittensory review-now\n@gittensory needs-author\n@gittensory duplicate-clusters\n@gittensory burden-forecast\n@gittensory intake-health\n@gittensory outcome-patterns\n@gittensory noise-report";

export const ACTION_COMMAND_ENTRIES = [
  {
    id: "gate-override",
    title: "Gate override",
    description:
      "Record a maintainer override for this commit's gate check only (does not persist across new commits).",
  },
  {
    id: "review",
    title: "Request review",
    description:
      "Request an auto-review run on the current PR head (`@gittensory re-review` is an alias).",
  },
  {
    id: "pause",
    title: "Pause auto-review",
    description:
      "Pause auto-review for this PR with an optional reason; does not change gate enforcement.",
  },
  {
    id: "resume",
    title: "Resume auto-review",
    description:
      "Resume auto-review for this PR with an optional reason; does not change gate enforcement.",
  },
  {
    id: "resolve",
    title: "Resolve finding",
    description:
      "Mark a review finding as resolved, optionally naming the finding in trailing text.",
  },
  {
    id: "configuration",
    title: "Show configuration",
    description: "Show the effective resolved review configuration for this repository.",
  },
  {
    id: "explain",
    title: "Explain finding",
    description:
      "Explain a specific review finding; supply the finding reference in trailing text.",
  },
] as const;

export const ACTION_COMMAND_LIST =
  "@gittensory gate-override\n@gittensory review\n@gittensory pause\n@gittensory resume\n@gittensory resolve\n@gittensory configuration\n@gittensory explain";
