// Generated by review-enrichment/scripts/generate-analyzer-metadata.mjs.
// Do not edit by hand; update review-enrichment analyzer descriptors instead.

export type ReesProfileName = "fast" | "balanced" | "deep";

export type ReesAnalyzerDoc = {
  name: string;
  title: string;
  category: string;
  cost: string;
  defaultEnabled: boolean;
  profiles: readonly ReesProfileName[];
  requires: readonly string[];
  limits: Readonly<Record<string, number>>;
  docs: {
    summary: string;
    looksAt: string;
    reports: string;
    network: string;
    notes: string;
  };
};

export type ReesProfileDoc = {
  name: ReesProfileName;
  default: boolean;
  costClasses: readonly string[];
  concurrency: Readonly<Record<string, number>>;
  timeoutMs: Readonly<Record<string, number>>;
  responseReserveMs: number;
};

export const REES_DEFAULT_PROFILE = "balanced" as const;

export const REES_PROFILES = [
  {
    name: "fast",
    default: false,
    costClasses: ["local", "registry"],
    concurrency: {
      local: 8,
      registry: 2,
      "github-light": 0,
      "github-heavy": 0,
      tooling: 0,
    },
    timeoutMs: {
      local: 400,
      registry: 800,
      "github-light": 0,
      "github-heavy": 0,
      tooling: 0,
    },
    responseReserveMs: 500,
  },
  {
    name: "balanced",
    default: true,
    costClasses: ["local", "registry", "github-light", "github-heavy", "tooling"],
    concurrency: {
      local: 8,
      registry: 3,
      "github-light": 2,
      "github-heavy": 1,
      tooling: 1,
    },
    timeoutMs: {
      local: 750,
      registry: 1400,
      "github-light": 1400,
      "github-heavy": 2200,
      tooling: 1400,
    },
    responseReserveMs: 750,
  },
  {
    name: "deep",
    default: false,
    costClasses: ["local", "registry", "github-light", "github-heavy", "tooling"],
    concurrency: {
      local: 8,
      registry: 4,
      "github-light": 2,
      "github-heavy": 1,
      tooling: 1,
    },
    timeoutMs: {
      local: 1000,
      registry: 2500,
      "github-light": 2500,
      "github-heavy": 4000,
      tooling: 2500,
    },
    responseReserveMs: 1000,
  },
] as const satisfies readonly ReesProfileDoc[];

export const REES_ANALYZERS = [
  {
    name: "dependency",
    title: "Dependency vulnerabilities",
    category: "supply-chain",
    cost: "registry",
    defaultEnabled: true,
    profiles: ["fast", "balanced", "deep"],
    requires: ["files", "public-network"],
    limits: {
      maxManifestFiles: 20,
      maxPatchLinesPerFile: 500,
      maxDependencyQueries: 25,
    },
    docs: {
      summary: "Checks changed direct dependency versions against OSV.dev.",
      looksAt:
        "Added or upgraded dependencies in package.json, requirements.txt, and go.mod diffs.",
      reports:
        "Known CVEs with severity, advisory id, summary, and fixed version when OSV publishes one.",
      network: "Calls OSV.dev. No GitHub token required.",
      notes: "Manifest-only by design; use lockfileDrift for transitive lockfile changes.",
    },
  },
  {
    name: "lockfileDrift",
    title: "Lockfile drift",
    category: "supply-chain",
    cost: "registry",
    defaultEnabled: true,
    profiles: ["fast", "balanced", "deep"],
    requires: ["files", "public-network"],
    limits: {
      maxLockfileFiles: 12,
      maxPatchLinesPerFile: 1200,
      maxOsvQueries: 40,
    },
    docs: {
      summary:
        "Finds vulnerable transitive dependency versions introduced only through lockfile changes.",
      looksAt:
        "package-lock.json, yarn.lock, and poetry.lock patches, excluding packages already named in a changed manifest.",
      reports:
        "Lockfile line, package/version, ecosystem, direction, and OSV vulnerability details.",
      network: "Calls OSV.dev querybatch. No GitHub token required.",
      notes:
        "Useful when a PR does not touch a top-level manifest but changes resolved dependency pins.",
    },
  },
  {
    name: "secret",
    title: "Hardcoded secrets",
    category: "security",
    cost: "local",
    defaultEnabled: true,
    profiles: ["fast", "balanced", "deep"],
    requires: ["files"],
    limits: {},
    docs: {
      summary: "Scans added diff lines for credential-shaped values.",
      looksAt: "Added lines in every changed file patch.",
      reports: "File, line, secret kind, and confidence. The matched value is never returned.",
      network: "Pure local analyzer. No external network call.",
      notes:
        "High-confidence patterns are treated as rotate-and-remove candidates; generic assignments stay verify-first.",
    },
  },
  {
    name: "license",
    title: "Dependency licenses",
    category: "supply-chain",
    cost: "registry",
    defaultEnabled: true,
    profiles: ["fast", "balanced", "deep"],
    requires: ["files", "public-network"],
    limits: {
      maxLicenseLookups: 25,
    },
    docs: {
      summary: "Checks licenses for newly added or upgraded dependencies.",
      looksAt: "The same direct dependency changes used by the dependency analyzer.",
      reports:
        "Copyleft or unknown license classifications that need maintainer compatibility review.",
      network: "Calls deps.dev. No GitHub token required.",
      notes: "Permissive and otherwise-known licenses are intentionally silent.",
    },
  },
  {
    name: "installScript",
    title: "npm install scripts",
    category: "supply-chain",
    cost: "registry",
    defaultEnabled: true,
    profiles: ["fast", "balanced", "deep"],
    requires: ["files", "public-network"],
    limits: {},
    docs: {
      summary: "Flags npm packages that run lifecycle hooks during install.",
      looksAt: "New or upgraded npm dependencies.",
      reports: "Package, version, hook names, and publish date when available.",
      network: "Calls the npm registry. No GitHub token required.",
      notes: "The script body is not returned, which keeps the brief compact and non-executable.",
    },
  },
  {
    name: "heavyDependency",
    title: "Heavy dependencies used trivially",
    category: "performance",
    cost: "registry",
    defaultEnabled: true,
    profiles: ["fast", "balanced", "deep"],
    requires: ["files", "public-network"],
    limits: {
      maxWeightLookups: 20,
      maxFindings: 15,
    },
    docs: {
      summary: "Flags materially heavy npm dependencies used only a few times in changed lines.",
      looksAt: "New or upgraded npm dependencies plus direct uses in added lines.",
      reports: "Package size, dependency count, usage count, and line-cited usage locations.",
      network: "Calls Bundlephobia. No GitHub token required.",
      notes: "Only reports packages with trivial direct usage so the finding stays actionable.",
    },
  },
  {
    name: "actionPin",
    title: "Unpinned GitHub Actions",
    category: "supply-chain",
    cost: "local",
    defaultEnabled: true,
    profiles: ["fast", "balanced", "deep"],
    requires: ["files"],
    limits: {},
    docs: {
      summary: "Detects third-party workflow actions pinned to mutable tags or branches.",
      looksAt: "Added uses: lines in .github/workflows YAML patches.",
      reports: "Workflow file, line, action, and mutable ref.",
      network: "Pure local analyzer. No external network call.",
      notes: "Official actions/* and github/* actions are excluded to keep the signal focused.",
    },
  },
  {
    name: "eol",
    title: "End-of-life runtimes",
    category: "supply-chain",
    cost: "registry",
    defaultEnabled: true,
    profiles: ["fast", "balanced", "deep"],
    requires: ["files", "public-network"],
    limits: {
      maxFiles: 40,
      maxPatchLines: 1000,
      maxPins: 80,
    },
    docs: {
      summary: "Checks changed runtime and base-image pins against EOL calendars.",
      looksAt: "Dockerfile FROM lines, .nvmrc, and go.mod runtime pins.",
      reports:
        "File, product, version, EOL date, and whether the release is already EOL or close to EOL.",
      network: "Calls endoflife.date. No GitHub token required.",
      notes:
        "Only changed pins are checked; existing old runtimes outside the PR are not reported.",
    },
  },
  {
    name: "redos",
    title: "ReDoS-prone regex",
    category: "security",
    cost: "local",
    defaultEnabled: true,
    profiles: ["fast", "balanced", "deep"],
    requires: ["files"],
    limits: {
      maxFindings: 25,
      maxPatternChars: 1000,
      maxLineChars: 2000,
    },
    docs: {
      summary: "Finds newly introduced regex shapes that can catastrophically backtrack.",
      looksAt: "Regex literals and RegExp constructor string arguments in added lines.",
      reports: "File, line, and a truncated vulnerable pattern.",
      network: "Pure local analyzer. No external network call.",
      notes:
        "Structural and precision-first; it flags nested unbounded quantifier shapes such as (a+)+.",
    },
  },
  {
    name: "provenance",
    title: "Provenance and committed artifacts",
    category: "supply-chain",
    cost: "registry",
    defaultEnabled: true,
    profiles: ["fast", "balanced", "deep"],
    requires: ["files", "public-network"],
    limits: {
      maxAttestationChecks: 20,
      maxFindings: 30,
    },
    docs: {
      summary: "Checks package attestations and reviewability of newly added artifacts.",
      looksAt: "New npm/PyPI dependency versions plus added binary, vendored, and minified files.",
      reports:
        "Missing attestations, binary files without reviewable source, and vendored or minified code.",
      network:
        "Calls npm and PyPI attestation/provenance endpoints for package checks. Path checks are local.",
      notes: "Network failures fail safe; it flags only confident no-attestation responses.",
    },
  },
  {
    name: "codeowners",
    title: "CODEOWNERS coverage",
    category: "ownership",
    cost: "github-light",
    defaultEnabled: true,
    profiles: ["balanced", "deep"],
    requires: ["files", "author", "github-token"],
    limits: {
      maxFilesReported: 20,
      maxCodeownersBytes: 65536,
      maxCodeownersRules: 1000,
    },
    docs: {
      summary: "Checks whether changed files cross ownership domains not owned by the PR author.",
      looksAt: ".github/CODEOWNERS, CODEOWNERS, or docs/CODEOWNERS plus the changed file list.",
      reports:
        "Owned files where the PR author is not listed, plus ownership blast-radius context in the rendered brief.",
      network:
        "Calls the GitHub API. Requires author plus GitHub token forwarding for private repos.",
      notes:
        "Leave REES_FORWARD_GITHUB_TOKEN unset/false to disable token forwarding; this analyzer will then skip when it cannot read CODEOWNERS.",
    },
  },
  {
    name: "secretLog",
    title: "Secrets or PII in logs",
    category: "security",
    cost: "local",
    defaultEnabled: true,
    profiles: ["fast", "balanced", "deep"],
    requires: ["files"],
    limits: {
      maxFindings: 25,
      maxLineChars: 2000,
    },
    docs: {
      summary: "Flags added code that writes sensitive values to logs or stdout.",
      looksAt: "Added lines that call console, logger, process.stdout, or process.stderr sinks.",
      reports: "File, line, sink, and category: secret, pii, or request-object.",
      network: "Pure local analyzer. No external network call.",
      notes:
        "String log messages are stripped before matching, so ordinary prose like password reset is not enough to trigger.",
    },
  },
  {
    name: "assetWeight",
    title: "Heavy binary assets",
    category: "performance",
    cost: "github-heavy",
    defaultEnabled: true,
    profiles: ["balanced", "deep"],
    requires: ["files", "github-token", "head-sha"],
    limits: {
      maxFindings: 50,
    },
    docs: {
      summary:
        "Finds large binary assets added to a PR, and growth deltas when base size is available.",
      looksAt:
        "Changed binary assets such as images, fonts, archives, PDFs, videos, and compiled binaries.",
      reports: "Path, size, delta, and whether the asset was added or grown.",
      network:
        "Calls the GitHub API. Requires headSha and GitHub token forwarding for private repos.",
      notes:
        "Added asset detection works from headSha. Growth comparison needs baseSha in the enrichment request.",
    },
  },
  {
    name: "typosquat",
    title: "Typosquat and dependency-confusion risk",
    category: "supply-chain",
    cost: "registry",
    defaultEnabled: true,
    profiles: ["fast", "balanced", "deep"],
    requires: ["files", "public-network"],
    limits: {
      maxDeps: 50,
      maxConfusionQueries: 15,
    },
    docs: {
      summary:
        "Checks newly added dependency names for near-miss and publicly claimable package names.",
      looksAt: "Newly added npm and PyPI dependency names.",
      reports:
        "Typosquat matches against popular packages, or unscoped names missing from the public registry.",
      network:
        "Uses bundled popular-package lists plus npm/PyPI registry lookups for dependency-confusion checks.",
      notes:
        "Scoped npm packages are treated as namespace-protected and are not flagged as typosquats.",
    },
  },
  {
    name: "commitSignature",
    title: "Head commit signature",
    category: "supply-chain",
    cost: "github-light",
    defaultEnabled: true,
    profiles: ["balanced", "deep"],
    requires: ["github-token", "head-sha"],
    limits: {},
    docs: {
      summary: "Checks head commit signature and public author provenance.",
      looksAt: "The head commit plus a bounded slice of recent repository commit history.",
      reports: "GitHub signature verification reason and public boolean provenance flags.",
      network:
        "Calls the GitHub API. Requires headSha and GitHub token forwarding for private repos.",
      notes:
        "Does not expose emails or private identity data; only public GitHub commit facts are surfaced.",
    },
  },
  {
    name: "iacMisconfig",
    title: "IaC / config misconfiguration",
    category: "config",
    cost: "local",
    defaultEnabled: true,
    profiles: ["fast", "balanced", "deep"],
    requires: ["files"],
    limits: {
      maxFindings: 25,
      maxLineChars: 2000,
    },
    docs: {
      summary: "Flags risky IaC/config changes such as public buckets or insecure CORS.",
      looksAt: "Added lines in Docker, Terraform, YAML, JSON, and similar config files.",
      reports: "File, line, and public-safe rule kind.",
      network: "Pure local analyzer. No external network call.",
      notes: "Reports configuration shapes only; it does not inspect private runtime config.",
    },
  },
  {
    name: "nativeBuild",
    title: "Native-build dependencies",
    category: "performance",
    cost: "registry",
    defaultEnabled: true,
    profiles: ["fast", "balanced", "deep"],
    requires: ["files", "public-network"],
    limits: {
      maxQueries: 25,
      maxRegistryJsonBytes: 2097152,
    },
    docs: {
      summary: "Flags newly-added dependencies that compile native code or ship sdist-only builds.",
      looksAt: "New npm/PyPI dependency versions.",
      reports: "Package, version, ecosystem, native-build kind, and public-safe reason.",
      network: "Calls npm and PyPI registries. No GitHub token required.",
      notes: "Registry JSON is capped so large package metadata cannot monopolize REES memory.",
    },
  },
  {
    name: "history",
    title: "Author and change-area history",
    category: "history",
    cost: "github-heavy",
    defaultEnabled: true,
    profiles: ["balanced", "deep"],
    requires: ["files", "github-token", "author"],
    limits: {
      maxFilesProbed: 5,
      commitsPerFile: 10,
      maxPrLookups: 12,
      maxSimilarPrs: 8,
    },
    docs: {
      summary:
        "Shows public author track record, same-file PR history, and linked-issue alignment.",
      looksAt:
        "The PR author, changed file paths, linked issue text, added diff lines, and bounded GitHub history lookups.",
      reports:
        "Prior PR counts, similar past PRs, linked issue coverage, and partial/degraded status.",
      network:
        "Calls GitHub API with bounded fanout. Requires author plus GitHub token forwarding for private repos.",
      notes:
        "Returns partial findings when GitHub lookups are skipped, capped, or budget-exhausted.",
    },
  },
  {
    name: "docCommentDrift",
    title: "Doc-comment drift",
    category: "quality",
    cost: "github-light",
    defaultEnabled: true,
    profiles: ["balanced", "deep"],
    requires: ["files", "github-token", "head-sha"],
    limits: {
      maxFiles: 20,
      maxFindings: 50,
    },
    docs: {
      summary:
        "Flags a JSDoc/TSDoc @param that names a parameter the PR removed or renamed but left documented.",
      looksAt:
        "Changed TS/JS source files at headSha, comparing each named function's old vs new parameter list.",
      reports: "File, line, function, and the stale parameter name(s).",
      network:
        "Calls the GitHub API for changed file contents. Requires headSha and token forwarding for private repos.",
      notes:
        "Conservative: only named function declarations with confidently-enumerable params; non-parameter signature edits are not reported.",
    },
  },
  {
    name: "duplication",
    title: "Near-verbatim duplicated code",
    category: "quality",
    cost: "github-light",
    defaultEnabled: true,
    profiles: ["balanced", "deep"],
    requires: ["files", "github-token", "head-sha"],
    limits: {
      minRun: 8,
      maxCandidates: 40,
      maxFetches: 30,
      maxFindings: 25,
      maxFileBytes: 500000,
    },
    docs: {
      summary:
        "Flags added code that is a near-verbatim duplicate of a block already present elsewhere in the repo.",
      looksAt:
        "Added diff hunks in changed source files compared against same-extension repo files fetched from the git tree at headSha.",
      reports:
        "The head file:line, the existing source file:line it duplicates, and the matched line count.",
      network:
        "Calls the GitHub API for the git tree and candidate blobs. Requires headSha and token forwarding for private repos.",
      notes:
        "Conservative: trivial/boilerplate lines are dropped and a long contiguous run is required, so incidental overlap is not flagged. Never returns code content.",
    },
  },
  {
    name: "churnHotspot",
    title: "Churn hotspots",
    category: "history",
    cost: "github-heavy",
    defaultEnabled: true,
    profiles: ["balanced", "deep"],
    requires: ["files", "github-token"],
    limits: {
      maxFilesProbed: 8,
      windowDays: 90,
      perPage: 100,
    },
    docs: {
      summary:
        "Flags changed files that are statistical fragility hotspots — high commit frequency and a high fix/revert fraction.",
      looksAt:
        "Each changed file's recent commit history (a 90-day window), excluding lockfiles, generated output, and binaries.",
      reports:
        "File, commit count, fix/revert count, and the window — counts only, never file contents.",
      network:
        "Calls the GitHub commits API once per probed file. Requires GitHub token forwarding for private repos.",
      notes:
        "Distinct from the history analyzer's author track record; this scores the change AREA's defect density.",
    },
  },
  {
    name: "blameLink",
    title: "Recent file history (last PR to touch)",
    category: "history",
    cost: "github-light",
    defaultEnabled: true,
    profiles: ["balanced", "deep"],
    requires: ["files", "github-token"],
    limits: {
      maxFilesProbed: 6,
      maxLookups: 12,
    },
    docs: {
      summary:
        "For files this PR modifies or deletes, surfaces the last PR to touch each file — file-level history context, not per-line blame.",
      looksAt:
        "Each changed file's most recent base-branch commit (bounded to the first few files) and that commit's associated PR.",
      reports:
        "File, a pointer to where this PR changes it, the last-touching PR number, and a short commit-SHA prefix — never file contents.",
      network:
        "Calls the GitHub commits API and the commit→PR association API, both bounded by a total lookup cap.",
      notes:
        "File-level, not per-line: it reports each file's most recent prior toucher, never claiming a specific line's origin. Fail-safe and partial on cap.",
    },
  },
] as const satisfies readonly ReesAnalyzerDoc[];

export const REES_ANALYZER_NAMES = REES_ANALYZERS.map((analyzer) => analyzer.name);
