// Generated by scripts/gen-selfhost-env-reference.mjs. Do not edit manually.
export type SelfHostEnvReferenceRow = {
  name: string;
  firstReference: string;
};

export const SELFHOST_ENV_REFERENCE_ROWS: SelfHostEnvReferenceRow[] = [
  {
    name: "AI_COMBINE",
    firstReference: "src/selfhost/ai.ts",
  },
  {
    name: "AI_DUAL_REVIEW",
    firstReference: "src/selfhost/ai.ts",
  },
  {
    name: "AI_EMBED_API_KEY",
    firstReference: "src/server.ts",
  },
  {
    name: "AI_EMBED_BASE_URL",
    firstReference: "src/server.ts",
  },
  {
    name: "AI_EMBED_MODEL",
    firstReference: "src/selfhost/ai.ts",
  },
  {
    name: "AI_ON_MERGE",
    firstReference: "src/selfhost/ai.ts",
  },
  {
    name: "AI_PROVIDER",
    firstReference: "src/selfhost/ai-config.ts",
  },
  {
    name: "AI_VISION_API_KEY",
    firstReference: "src/server.ts",
  },
  {
    name: "AI_VISION_BASE_URL",
    firstReference: "src/server.ts",
  },
  {
    name: "AI_VISION_MODEL",
    firstReference: "src/server.ts",
  },
  {
    name: "ANTHROPIC_AI_BASE_URL",
    firstReference: "src/selfhost/ai.ts",
  },
  {
    name: "ANTHROPIC_AI_MODEL",
    firstReference: "src/selfhost/ai.ts",
  },
  {
    name: "ANTHROPIC_API_KEY",
    firstReference: "src/selfhost/ai.ts",
  },
  {
    name: "BACKUP_ACKNOWLEDGED",
    firstReference: "src/server.ts",
  },
  {
    name: "BROWSER_WS_ENDPOINT",
    firstReference: "src/selfhost/stubs/puppeteer.ts",
  },
  {
    name: "CLAUDE_AI_EFFORT",
    firstReference: "src/selfhost/ai.ts",
  },
  {
    name: "CLAUDE_AI_MODEL",
    firstReference: "src/selfhost/ai.ts",
  },
  {
    name: "CLAUDE_AI_TIMEOUT_MS",
    firstReference: "src/selfhost/ai.ts",
  },
  {
    name: "CLOUDFLARE_D1_MONITOR_ACCOUNT_ID",
    firstReference: "src/selfhost/d1-size-probe.ts",
  },
  {
    name: "CLOUDFLARE_D1_MONITOR_API_TOKEN",
    firstReference: "src/selfhost/d1-size-probe.ts",
  },
  {
    name: "CLOUDFLARE_D1_MONITOR_DATABASE_ID",
    firstReference: "src/selfhost/d1-size-probe.ts",
  },
  {
    name: "CODEX_AI_EFFORT",
    firstReference: "src/selfhost/ai.ts",
  },
  {
    name: "CODEX_AI_FIRST_OUTPUT_TIMEOUT_MS",
    firstReference: "src/selfhost/ai.ts",
  },
  {
    name: "CODEX_AI_MODEL",
    firstReference: "src/selfhost/ai.ts",
  },
  {
    name: "CODEX_AI_TIMEOUT_MS",
    firstReference: "src/selfhost/ai.ts",
  },
  {
    name: "CODEX_HOME",
    firstReference: "src/selfhost/ai.ts",
  },
  {
    name: "CRON_INTERVAL_MS",
    firstReference: "src/server.ts",
  },
  {
    name: "DATABASE_PATH",
    firstReference: "src/server.ts",
  },
  {
    name: "DATABASE_URL",
    firstReference: "src/selfhost/preflight.ts",
  },
  {
    name: "DISCORD_REPO_WEBHOOKS",
    firstReference: "src/services/notify-discord.ts",
  },
  {
    name: "DISCORD_WEBHOOK_URL",
    firstReference: "src/services/notify-discord.ts",
  },
  {
    name: "FOREGROUND_LIVENESS_CHECK_INTERVAL_MS",
    firstReference: "src/selfhost/foreground-liveness.ts",
  },
  {
    name: "FOREGROUND_LIVENESS_ENABLED",
    firstReference: "src/selfhost/foreground-liveness.ts",
  },
  {
    name: "FOREGROUND_LIVENESS_MAX_DEFER_MS",
    firstReference: "src/selfhost/foreground-liveness.ts",
  },
  {
    name: "FOREGROUND_LIVENESS_MAX_RELEASE_PER_SWEEP",
    firstReference: "src/selfhost/foreground-liveness.ts",
  },
  {
    name: "GITHUB_APP_ID",
    firstReference: "src/selfhost/orb-collector.ts",
  },
  {
    name: "GITHUB_APP_PRIVATE_KEY",
    firstReference: "src/selfhost/orb-collector.ts",
  },
  {
    name: "GITHUB_CACHE_TTL_SECONDS",
    firstReference: "src/server.ts",
  },
  {
    name: "GITHUB_INSTALLATION_CONCURRENCY_DEFER_MS",
    firstReference: "src/selfhost/installation-concurrency-admission.ts",
  },
  {
    name: "GITHUB_INSTALLATION_CONCURRENCY_ENABLED",
    firstReference: "src/selfhost/installation-concurrency-admission.ts",
  },
  {
    name: "GITHUB_INSTALLATION_CONCURRENCY_LIMIT",
    firstReference: "src/selfhost/installation-concurrency-admission.ts",
  },
  {
    name: "GITTENSORY_REPO_CONFIG_DIR",
    firstReference: "src/server.ts",
  },
  {
    name: "GITTENSORY_VERSION",
    firstReference: "src/selfhost/otel.ts",
  },
  {
    name: "HOME",
    firstReference: "src/selfhost/ai.ts",
  },
  {
    name: "MAINTENANCE_ADMISSION_DEFER_MS",
    firstReference: "src/selfhost/maintenance-admission.ts",
  },
  {
    name: "MAINTENANCE_ADMISSION_DRAIN_AGE_MS",
    firstReference: "src/selfhost/maintenance-admission.ts",
  },
  {
    name: "MAINTENANCE_ADMISSION_ENABLED",
    firstReference: "src/selfhost/maintenance-admission.ts",
  },
  {
    name: "MAINTENANCE_ADMISSION_MAX_BACKLOG_CONVERGENCE_PENDING",
    firstReference: "src/selfhost/maintenance-admission.ts",
  },
  {
    name: "MAINTENANCE_ADMISSION_MAX_DEFER_AGE_MS",
    firstReference: "src/selfhost/maintenance-admission.ts",
  },
  {
    name: "MAINTENANCE_ADMISSION_MAX_LIVE_AGE_MS",
    firstReference: "src/selfhost/maintenance-admission.ts",
  },
  {
    name: "MAINTENANCE_ADMISSION_MAX_LIVE_PENDING",
    firstReference: "src/selfhost/maintenance-admission.ts",
  },
  {
    name: "MAINTENANCE_ADMISSION_MAX_PENDING",
    firstReference: "src/selfhost/maintenance-admission.ts",
  },
  {
    name: "MIGRATIONS_DIR",
    firstReference: "src/server.ts",
  },
  {
    name: "OBSERVABILITY_SMOKE_POLL_MS",
    firstReference: "scripts/smoke-observability-traces.mjs",
  },
  {
    name: "OBSERVABILITY_SMOKE_TIMEOUT_MS",
    firstReference: "scripts/smoke-observability-traces.mjs",
  },
  {
    name: "OLLAMA_AI_API_KEY",
    firstReference: "src/selfhost/ai.ts",
  },
  {
    name: "OLLAMA_AI_BASE_URL",
    firstReference: "src/selfhost/ai.ts",
  },
  {
    name: "OLLAMA_AI_MODEL",
    firstReference: "src/selfhost/ai.ts",
  },
  {
    name: "OPENAI_AI_BASE_URL",
    firstReference: "src/selfhost/ai.ts",
  },
  {
    name: "OPENAI_AI_MODEL",
    firstReference: "src/selfhost/ai.ts",
  },
  {
    name: "OPENAI_API_KEY",
    firstReference: "src/selfhost/ai.ts",
  },
  {
    name: "OPENAI_COMPATIBLE_AI_API_KEY",
    firstReference: "src/selfhost/ai.ts",
  },
  {
    name: "OPENAI_COMPATIBLE_AI_BASE_URL",
    firstReference: "src/selfhost/ai.ts",
  },
  {
    name: "OPENAI_COMPATIBLE_AI_MODEL",
    firstReference: "src/selfhost/ai.ts",
  },
  {
    name: "ORB_AIR_GAP",
    firstReference: "src/selfhost/orb-collector.ts",
  },
  {
    name: "ORB_ANONYMIZE",
    firstReference: "src/selfhost/orb-collector.ts",
  },
  {
    name: "ORB_APP_ID",
    firstReference: "src/selfhost/orb-collector.ts",
  },
  {
    name: "ORB_BROKER_URL",
    firstReference: "src/server.ts",
  },
  {
    name: "ORB_COLLECTOR_TOKEN",
    firstReference: "src/selfhost/orb-collector.ts",
  },
  {
    name: "ORB_COLLECTOR_URL",
    firstReference: "src/selfhost/orb-collector.ts",
  },
  {
    name: "ORB_ENROLLMENT_SECRET",
    firstReference: "src/selfhost/orb-collector.ts",
  },
  {
    name: "ORB_RELAY_MODE",
    firstReference: "src/server.ts",
  },
  {
    name: "OTEL_EXPORTER_OTLP_ENDPOINT",
    firstReference: "src/selfhost/otel.ts",
  },
  {
    name: "OTEL_EXPORTER_OTLP_TRACES_ENDPOINT",
    firstReference: "src/selfhost/otel.ts",
  },
  {
    name: "OTEL_SERVICE_ENVIRONMENT",
    firstReference: "src/selfhost/otel.ts",
  },
  {
    name: "OTEL_SERVICE_NAME",
    firstReference: "src/selfhost/otel.ts",
  },
  {
    name: "OTEL_TRACES_EXPORTER",
    firstReference: "src/selfhost/otel.ts",
  },
  {
    name: "OTEL_TRACES_SAMPLER",
    firstReference: "src/selfhost/otel.ts",
  },
  {
    name: "OTEL_TRACES_SAMPLER_ARG",
    firstReference: "src/selfhost/otel.ts",
  },
  {
    name: "PGPOOL_MAX",
    firstReference: "src/selfhost/queue-common.ts",
  },
  {
    name: "PGVECTOR_ENABLED",
    firstReference: "src/server.ts",
  },
  {
    name: "PORT",
    firstReference: "src/server.ts",
  },
  {
    name: "PUBLIC_API_ORIGIN",
    firstReference: "src/selfhost/preflight.ts",
  },
  {
    name: "PUBLIC_ORIGIN_ACKNOWLEDGED",
    firstReference: "src/server.ts",
  },
  {
    name: "PUBLIC_SITE_ORIGIN",
    firstReference: "src/server.ts",
  },
  {
    name: "QDRANT_API_KEY",
    firstReference: "src/selfhost/qdrant-vectorize.ts",
  },
  {
    name: "QDRANT_DIM",
    firstReference: "src/selfhost/qdrant-vectorize.ts",
  },
  {
    name: "QDRANT_URL",
    firstReference: "src/server.ts",
  },
  {
    name: "QUEUE_BACKGROUND_CONCURRENCY",
    firstReference: "src/selfhost/queue-common.ts",
  },
  {
    name: "QUEUE_CONCURRENCY",
    firstReference: "src/selfhost/pg-queue.ts",
  },
  {
    name: "QUEUE_DEAD_LETTER_AUTO_RETRY_MAX_EXTRA_ATTEMPTS",
    firstReference: "src/selfhost/queue-common.ts",
  },
  {
    name: "QUEUE_STARTUP_JITTER_MIN_JOBS",
    firstReference: "src/selfhost/queue-common.ts",
  },
  {
    name: "REDIS_URL",
    firstReference: "src/selfhost/preflight.ts",
  },
  {
    name: "REVIEW_AUDIT_DIR",
    firstReference: "src/server.ts",
  },
  {
    name: "REVIEW_AUDIT_S3_ACCESS_KEY_ID",
    firstReference: "src/server.ts",
  },
  {
    name: "REVIEW_AUDIT_S3_BUCKET",
    firstReference: "src/server.ts",
  },
  {
    name: "REVIEW_AUDIT_S3_ENDPOINT",
    firstReference: "src/server.ts",
  },
  {
    name: "REVIEW_AUDIT_S3_REGION",
    firstReference: "src/server.ts",
  },
  {
    name: "REVIEW_AUDIT_S3_SECRET_ACCESS_KEY",
    firstReference: "src/server.ts",
  },
  {
    name: "SELFHOST_BUNDLE_ALL",
    firstReference: "scripts/build-selfhost.mjs",
  },
  {
    name: "SELFHOST_SERVICE",
    firstReference: "scripts/smoke-observability-traces.mjs",
  },
  {
    name: "SELFHOST_SETUP_TOKEN",
    firstReference: "src/selfhost/preflight.ts",
  },
  {
    name: "SENTRY_DSN",
    firstReference: "src/selfhost/sentry.ts",
  },
  {
    name: "SENTRY_ENVIRONMENT",
    firstReference: "src/selfhost/otel.ts",
  },
  {
    name: "SENTRY_RELEASE",
    firstReference: "src/selfhost/otel.ts",
  },
  {
    name: "SENTRY_SERVER_NAME",
    firstReference: "src/selfhost/sentry.ts",
  },
  {
    name: "SENTRY_TRACES_SAMPLE_RATE",
    firstReference: "src/selfhost/sentry.ts",
  },
  {
    name: "SETUP_OUTPUT_PATH",
    firstReference: "src/server.ts",
  },
  {
    name: "SLACK_WEBHOOK_URL",
    firstReference: "src/services/notify-discord.ts",
  },
];

export const SELFHOST_ENV_REFERENCE_MARKDOWN = [
  "| Name | First reference |",
  "| --- | --- |",
  "| `AI_COMBINE` | `src/selfhost/ai.ts` |",
  "| `AI_DUAL_REVIEW` | `src/selfhost/ai.ts` |",
  "| `AI_EMBED_API_KEY` | `src/server.ts` |",
  "| `AI_EMBED_BASE_URL` | `src/server.ts` |",
  "| `AI_EMBED_MODEL` | `src/selfhost/ai.ts` |",
  "| `AI_ON_MERGE` | `src/selfhost/ai.ts` |",
  "| `AI_PROVIDER` | `src/selfhost/ai-config.ts` |",
  "| `AI_VISION_API_KEY` | `src/server.ts` |",
  "| `AI_VISION_BASE_URL` | `src/server.ts` |",
  "| `AI_VISION_MODEL` | `src/server.ts` |",
  "| `ANTHROPIC_AI_BASE_URL` | `src/selfhost/ai.ts` |",
  "| `ANTHROPIC_AI_MODEL` | `src/selfhost/ai.ts` |",
  "| `ANTHROPIC_API_KEY` | `src/selfhost/ai.ts` |",
  "| `BACKUP_ACKNOWLEDGED` | `src/server.ts` |",
  "| `BROWSER_WS_ENDPOINT` | `src/selfhost/stubs/puppeteer.ts` |",
  "| `CLAUDE_AI_EFFORT` | `src/selfhost/ai.ts` |",
  "| `CLAUDE_AI_MODEL` | `src/selfhost/ai.ts` |",
  "| `CLAUDE_AI_TIMEOUT_MS` | `src/selfhost/ai.ts` |",
  "| `CLOUDFLARE_D1_MONITOR_ACCOUNT_ID` | `src/selfhost/d1-size-probe.ts` |",
  "| `CLOUDFLARE_D1_MONITOR_API_TOKEN` | `src/selfhost/d1-size-probe.ts` |",
  "| `CLOUDFLARE_D1_MONITOR_DATABASE_ID` | `src/selfhost/d1-size-probe.ts` |",
  "| `CODEX_AI_EFFORT` | `src/selfhost/ai.ts` |",
  "| `CODEX_AI_FIRST_OUTPUT_TIMEOUT_MS` | `src/selfhost/ai.ts` |",
  "| `CODEX_AI_MODEL` | `src/selfhost/ai.ts` |",
  "| `CODEX_AI_TIMEOUT_MS` | `src/selfhost/ai.ts` |",
  "| `CODEX_HOME` | `src/selfhost/ai.ts` |",
  "| `CRON_INTERVAL_MS` | `src/server.ts` |",
  "| `DATABASE_PATH` | `src/server.ts` |",
  "| `DATABASE_URL` | `src/selfhost/preflight.ts` |",
  "| `DISCORD_REPO_WEBHOOKS` | `src/services/notify-discord.ts` |",
  "| `DISCORD_WEBHOOK_URL` | `src/services/notify-discord.ts` |",
  "| `FOREGROUND_LIVENESS_CHECK_INTERVAL_MS` | `src/selfhost/foreground-liveness.ts` |",
  "| `FOREGROUND_LIVENESS_ENABLED` | `src/selfhost/foreground-liveness.ts` |",
  "| `FOREGROUND_LIVENESS_MAX_DEFER_MS` | `src/selfhost/foreground-liveness.ts` |",
  "| `FOREGROUND_LIVENESS_MAX_RELEASE_PER_SWEEP` | `src/selfhost/foreground-liveness.ts` |",
  "| `GITHUB_APP_ID` | `src/selfhost/orb-collector.ts` |",
  "| `GITHUB_APP_PRIVATE_KEY` | `src/selfhost/orb-collector.ts` |",
  "| `GITHUB_CACHE_TTL_SECONDS` | `src/server.ts` |",
  "| `GITHUB_INSTALLATION_CONCURRENCY_DEFER_MS` | `src/selfhost/installation-concurrency-admission.ts` |",
  "| `GITHUB_INSTALLATION_CONCURRENCY_ENABLED` | `src/selfhost/installation-concurrency-admission.ts` |",
  "| `GITHUB_INSTALLATION_CONCURRENCY_LIMIT` | `src/selfhost/installation-concurrency-admission.ts` |",
  "| `GITTENSORY_REPO_CONFIG_DIR` | `src/server.ts` |",
  "| `GITTENSORY_VERSION` | `src/selfhost/otel.ts` |",
  "| `HOME` | `src/selfhost/ai.ts` |",
  "| `MAINTENANCE_ADMISSION_DEFER_MS` | `src/selfhost/maintenance-admission.ts` |",
  "| `MAINTENANCE_ADMISSION_DRAIN_AGE_MS` | `src/selfhost/maintenance-admission.ts` |",
  "| `MAINTENANCE_ADMISSION_ENABLED` | `src/selfhost/maintenance-admission.ts` |",
  "| `MAINTENANCE_ADMISSION_MAX_BACKLOG_CONVERGENCE_PENDING` | `src/selfhost/maintenance-admission.ts` |",
  "| `MAINTENANCE_ADMISSION_MAX_DEFER_AGE_MS` | `src/selfhost/maintenance-admission.ts` |",
  "| `MAINTENANCE_ADMISSION_MAX_LIVE_AGE_MS` | `src/selfhost/maintenance-admission.ts` |",
  "| `MAINTENANCE_ADMISSION_MAX_LIVE_PENDING` | `src/selfhost/maintenance-admission.ts` |",
  "| `MAINTENANCE_ADMISSION_MAX_PENDING` | `src/selfhost/maintenance-admission.ts` |",
  "| `MIGRATIONS_DIR` | `src/server.ts` |",
  "| `OBSERVABILITY_SMOKE_POLL_MS` | `scripts/smoke-observability-traces.mjs` |",
  "| `OBSERVABILITY_SMOKE_TIMEOUT_MS` | `scripts/smoke-observability-traces.mjs` |",
  "| `OLLAMA_AI_API_KEY` | `src/selfhost/ai.ts` |",
  "| `OLLAMA_AI_BASE_URL` | `src/selfhost/ai.ts` |",
  "| `OLLAMA_AI_MODEL` | `src/selfhost/ai.ts` |",
  "| `OPENAI_AI_BASE_URL` | `src/selfhost/ai.ts` |",
  "| `OPENAI_AI_MODEL` | `src/selfhost/ai.ts` |",
  "| `OPENAI_API_KEY` | `src/selfhost/ai.ts` |",
  "| `OPENAI_COMPATIBLE_AI_API_KEY` | `src/selfhost/ai.ts` |",
  "| `OPENAI_COMPATIBLE_AI_BASE_URL` | `src/selfhost/ai.ts` |",
  "| `OPENAI_COMPATIBLE_AI_MODEL` | `src/selfhost/ai.ts` |",
  "| `ORB_AIR_GAP` | `src/selfhost/orb-collector.ts` |",
  "| `ORB_ANONYMIZE` | `src/selfhost/orb-collector.ts` |",
  "| `ORB_APP_ID` | `src/selfhost/orb-collector.ts` |",
  "| `ORB_BROKER_URL` | `src/server.ts` |",
  "| `ORB_COLLECTOR_TOKEN` | `src/selfhost/orb-collector.ts` |",
  "| `ORB_COLLECTOR_URL` | `src/selfhost/orb-collector.ts` |",
  "| `ORB_ENROLLMENT_SECRET` | `src/selfhost/orb-collector.ts` |",
  "| `ORB_RELAY_MODE` | `src/server.ts` |",
  "| `OTEL_EXPORTER_OTLP_ENDPOINT` | `src/selfhost/otel.ts` |",
  "| `OTEL_EXPORTER_OTLP_TRACES_ENDPOINT` | `src/selfhost/otel.ts` |",
  "| `OTEL_SERVICE_ENVIRONMENT` | `src/selfhost/otel.ts` |",
  "| `OTEL_SERVICE_NAME` | `src/selfhost/otel.ts` |",
  "| `OTEL_TRACES_EXPORTER` | `src/selfhost/otel.ts` |",
  "| `OTEL_TRACES_SAMPLER` | `src/selfhost/otel.ts` |",
  "| `OTEL_TRACES_SAMPLER_ARG` | `src/selfhost/otel.ts` |",
  "| `PGPOOL_MAX` | `src/selfhost/queue-common.ts` |",
  "| `PGVECTOR_ENABLED` | `src/server.ts` |",
  "| `PORT` | `src/server.ts` |",
  "| `PUBLIC_API_ORIGIN` | `src/selfhost/preflight.ts` |",
  "| `PUBLIC_ORIGIN_ACKNOWLEDGED` | `src/server.ts` |",
  "| `PUBLIC_SITE_ORIGIN` | `src/server.ts` |",
  "| `QDRANT_API_KEY` | `src/selfhost/qdrant-vectorize.ts` |",
  "| `QDRANT_DIM` | `src/selfhost/qdrant-vectorize.ts` |",
  "| `QDRANT_URL` | `src/server.ts` |",
  "| `QUEUE_BACKGROUND_CONCURRENCY` | `src/selfhost/queue-common.ts` |",
  "| `QUEUE_CONCURRENCY` | `src/selfhost/pg-queue.ts` |",
  "| `QUEUE_DEAD_LETTER_AUTO_RETRY_MAX_EXTRA_ATTEMPTS` | `src/selfhost/queue-common.ts` |",
  "| `QUEUE_STARTUP_JITTER_MIN_JOBS` | `src/selfhost/queue-common.ts` |",
  "| `REDIS_URL` | `src/selfhost/preflight.ts` |",
  "| `REVIEW_AUDIT_DIR` | `src/server.ts` |",
  "| `REVIEW_AUDIT_S3_ACCESS_KEY_ID` | `src/server.ts` |",
  "| `REVIEW_AUDIT_S3_BUCKET` | `src/server.ts` |",
  "| `REVIEW_AUDIT_S3_ENDPOINT` | `src/server.ts` |",
  "| `REVIEW_AUDIT_S3_REGION` | `src/server.ts` |",
  "| `REVIEW_AUDIT_S3_SECRET_ACCESS_KEY` | `src/server.ts` |",
  "| `SELFHOST_BUNDLE_ALL` | `scripts/build-selfhost.mjs` |",
  "| `SELFHOST_SERVICE` | `scripts/smoke-observability-traces.mjs` |",
  "| `SELFHOST_SETUP_TOKEN` | `src/selfhost/preflight.ts` |",
  "| `SENTRY_DSN` | `src/selfhost/sentry.ts` |",
  "| `SENTRY_ENVIRONMENT` | `src/selfhost/otel.ts` |",
  "| `SENTRY_RELEASE` | `src/selfhost/otel.ts` |",
  "| `SENTRY_SERVER_NAME` | `src/selfhost/sentry.ts` |",
  "| `SENTRY_TRACES_SAMPLE_RATE` | `src/selfhost/sentry.ts` |",
  "| `SETUP_OUTPUT_PATH` | `src/server.ts` |",
  "| `SLACK_WEBHOOK_URL` | `src/services/notify-discord.ts` |",
].join("\n");
