// Generated by scripts/gen-selfhost-env-reference.mjs. Do not edit manually.
export type SelfHostEnvReferenceRow = {
  name: string;
  firstReference: string;
};

export const SELFHOST_ENV_REFERENCE_ROWS: SelfHostEnvReferenceRow[] = [
  {
    name: "AI_COMBINE",
    firstReference: "src/selfhost/ai.ts:936",
  },
  {
    name: "AI_EMBED_API_KEY",
    firstReference: "src/server.ts:428",
  },
  {
    name: "AI_EMBED_BASE_URL",
    firstReference: "src/server.ts:425",
  },
  {
    name: "AI_EMBED_MODEL",
    firstReference: "src/selfhost/ai.ts:832",
  },
  {
    name: "AI_ON_MERGE",
    firstReference: "src/selfhost/ai.ts:938",
  },
  {
    name: "AI_PROVIDER",
    firstReference: "src/selfhost/ai-config.ts:43",
  },
  {
    name: "ANTHROPIC_AI_BASE_URL",
    firstReference: "src/selfhost/ai.ts:836",
  },
  {
    name: "ANTHROPIC_AI_MODEL",
    firstReference: "src/selfhost/ai.ts:57",
  },
  {
    name: "ANTHROPIC_API_KEY",
    firstReference: "src/selfhost/ai.ts:835",
  },
  {
    name: "BACKUP_ACKNOWLEDGED",
    firstReference: "src/server.ts:367",
  },
  {
    name: "BROWSER_WS_ENDPOINT",
    firstReference: "src/selfhost/stubs/puppeteer.ts:11",
  },
  {
    name: "CLAUDE_AI_EFFORT",
    firstReference: "src/selfhost/ai.ts:108",
  },
  {
    name: "CLAUDE_AI_MODEL",
    firstReference: "src/selfhost/ai.ts:49",
  },
  {
    name: "CLAUDE_AI_TIMEOUT_MS",
    firstReference: "src/selfhost/ai.ts:108",
  },
  {
    name: "CODEX_AI_EFFORT",
    firstReference: "src/selfhost/ai.ts:112",
  },
  {
    name: "CODEX_AI_MODEL",
    firstReference: "src/selfhost/ai.ts:53",
  },
  {
    name: "CODEX_AI_TIMEOUT_MS",
    firstReference: "src/selfhost/ai.ts:112",
  },
  {
    name: "CODEX_HOME",
    firstReference: "src/selfhost/ai.ts:274",
  },
  {
    name: "CRON_INTERVAL_MS",
    firstReference: "src/server.ts:904",
  },
  {
    name: "DATABASE_PATH",
    firstReference: "src/server.ts:250",
  },
  {
    name: "DATABASE_URL",
    firstReference: "src/selfhost/preflight.ts:201",
  },
  {
    name: "DISCORD_REPO_WEBHOOKS",
    firstReference: "src/services/notify-discord.ts:41",
  },
  {
    name: "DISCORD_WEBHOOK_URL",
    firstReference: "src/services/notify-discord.ts:78",
  },
  {
    name: "FOREGROUND_LIVENESS_ENABLED",
    firstReference: "src/selfhost/foreground-liveness.ts:41",
  },
  {
    name: "GITHUB_APP_ID",
    firstReference: "src/selfhost/orb-collector.ts:59",
  },
  {
    name: "GITHUB_APP_PRIVATE_KEY",
    firstReference: "src/selfhost/orb-collector.ts:166",
  },
  {
    name: "GITHUB_CACHE_TTL_SECONDS",
    firstReference: "src/server.ts:496",
  },
  {
    name: "GITTENSORY_REPO_CONFIG_DIR",
    firstReference: "src/server.ts:284",
  },
  {
    name: "GITTENSORY_VERSION",
    firstReference: "src/selfhost/health.ts:29",
  },
  {
    name: "HOME",
    firstReference: "src/selfhost/ai.ts:274",
  },
  {
    name: "MAINTENANCE_ADMISSION_ENABLED",
    firstReference: "src/selfhost/maintenance-admission.ts:129",
  },
  {
    name: "MIGRATIONS_DIR",
    firstReference: "src/server.ts:380",
  },
  {
    name: "OBSERVABILITY_SMOKE_POLL_MS",
    firstReference: "scripts/smoke-observability-traces.mjs:8",
  },
  {
    name: "OBSERVABILITY_SMOKE_TIMEOUT_MS",
    firstReference: "scripts/smoke-observability-traces.mjs:6",
  },
  {
    name: "OLLAMA_AI_API_KEY",
    firstReference: "src/selfhost/ai.ts:829",
  },
  {
    name: "OLLAMA_AI_BASE_URL",
    firstReference: "src/selfhost/ai.ts:825",
  },
  {
    name: "OLLAMA_AI_MODEL",
    firstReference: "src/selfhost/ai.ts:61",
  },
  {
    name: "OPENAI_AI_BASE_URL",
    firstReference: "src/selfhost/ai.ts:827",
  },
  {
    name: "OPENAI_AI_MODEL",
    firstReference: "src/selfhost/ai.ts:62",
  },
  {
    name: "OPENAI_API_KEY",
    firstReference: "src/selfhost/ai.ts:829",
  },
  {
    name: "OPENAI_COMPATIBLE_AI_API_KEY",
    firstReference: "src/selfhost/ai.ts:829",
  },
  {
    name: "OPENAI_COMPATIBLE_AI_BASE_URL",
    firstReference: "src/selfhost/ai.ts:828",
  },
  {
    name: "OPENAI_COMPATIBLE_AI_MODEL",
    firstReference: "src/selfhost/ai.ts:63",
  },
  {
    name: "ORB_AIR_GAP",
    firstReference: "src/selfhost/orb-collector.ts:161",
  },
  {
    name: "ORB_ANONYMIZE",
    firstReference: "src/selfhost/orb-collector.ts:174",
  },
  {
    name: "ORB_APP_ID",
    firstReference: "src/selfhost/orb-collector.ts:59",
  },
  {
    name: "ORB_BROKER_URL",
    firstReference: "src/server.ts:953",
  },
  {
    name: "ORB_COLLECTOR_TOKEN",
    firstReference: "src/selfhost/orb-collector.ts:205",
  },
  {
    name: "ORB_COLLECTOR_URL",
    firstReference: "src/selfhost/orb-collector.ts:172",
  },
  {
    name: "ORB_ENROLLMENT_SECRET",
    firstReference: "src/selfhost/orb-collector.ts:165",
  },
  {
    name: "ORB_RELAY_MODE",
    firstReference: "src/server.ts:955",
  },
  {
    name: "OTEL_EXPORTER_OTLP_ENDPOINT",
    firstReference: "src/selfhost/otel.ts:47",
  },
  {
    name: "OTEL_EXPORTER_OTLP_TRACES_ENDPOINT",
    firstReference: "src/selfhost/otel.ts:45",
  },
  {
    name: "OTEL_SERVICE_ENVIRONMENT",
    firstReference: "src/selfhost/otel.ts:60",
  },
  {
    name: "OTEL_SERVICE_NAME",
    firstReference: "src/selfhost/otel.ts:59",
  },
  {
    name: "OTEL_TRACES_EXPORTER",
    firstReference: "src/selfhost/otel.ts:40",
  },
  {
    name: "OTEL_TRACES_SAMPLER",
    firstReference: "src/selfhost/otel.ts:74",
  },
  {
    name: "OTEL_TRACES_SAMPLER_ARG",
    firstReference: "src/selfhost/otel.ts:76",
  },
  {
    name: "PGVECTOR_ENABLED",
    firstReference: "src/server.ts:230",
  },
  {
    name: "PORT",
    firstReference: "src/server.ts:703",
  },
  {
    name: "PUBLIC_API_ORIGIN",
    firstReference: "src/selfhost/preflight.ts:192",
  },
  {
    name: "QDRANT_API_KEY",
    firstReference: "src/selfhost/qdrant-vectorize.ts:50",
  },
  {
    name: "QDRANT_DIM",
    firstReference: "src/selfhost/qdrant-vectorize.ts:71",
  },
  {
    name: "QDRANT_URL",
    firstReference: "src/server.ts:515",
  },
  {
    name: "QUEUE_BACKGROUND_CONCURRENCY",
    firstReference: "src/selfhost/queue-common.ts:102",
  },
  {
    name: "REDIS_URL",
    firstReference: "src/selfhost/preflight.ts:144",
  },
  {
    name: "REVIEW_AUDIT_DIR",
    firstReference: "src/server.ts:560",
  },
  {
    name: "SELFHOST_BUNDLE_ALL",
    firstReference: "scripts/build-selfhost.mjs:13",
  },
  {
    name: "SELFHOST_SERVICE",
    firstReference: "scripts/smoke-observability-traces.mjs:5",
  },
  {
    name: "SELFHOST_SETUP_TOKEN",
    firstReference: "src/selfhost/preflight.ts:186",
  },
  {
    name: "SENTRY_DSN",
    firstReference: "src/selfhost/sentry.ts:365",
  },
  {
    name: "SENTRY_ENVIRONMENT",
    firstReference: "src/selfhost/otel.ts:60",
  },
  {
    name: "SENTRY_RELEASE",
    firstReference: "src/selfhost/otel.ts:62",
  },
  {
    name: "SENTRY_SERVER_NAME",
    firstReference: "src/selfhost/sentry.ts:383",
  },
  {
    name: "SENTRY_TRACES_SAMPLE_RATE",
    firstReference: "src/selfhost/sentry.ts:171",
  },
  {
    name: "SETUP_OUTPUT_PATH",
    firstReference: "src/server.ts:820",
  },
];

export const SELFHOST_ENV_REFERENCE_MARKDOWN = [
  "| Name | First reference |",
  "| --- | --- |",
  "| `AI_COMBINE` | `src/selfhost/ai.ts:936` |",
  "| `AI_EMBED_API_KEY` | `src/server.ts:428` |",
  "| `AI_EMBED_BASE_URL` | `src/server.ts:425` |",
  "| `AI_EMBED_MODEL` | `src/selfhost/ai.ts:832` |",
  "| `AI_ON_MERGE` | `src/selfhost/ai.ts:938` |",
  "| `AI_PROVIDER` | `src/selfhost/ai-config.ts:43` |",
  "| `ANTHROPIC_AI_BASE_URL` | `src/selfhost/ai.ts:836` |",
  "| `ANTHROPIC_AI_MODEL` | `src/selfhost/ai.ts:57` |",
  "| `ANTHROPIC_API_KEY` | `src/selfhost/ai.ts:835` |",
  "| `BACKUP_ACKNOWLEDGED` | `src/server.ts:367` |",
  "| `BROWSER_WS_ENDPOINT` | `src/selfhost/stubs/puppeteer.ts:11` |",
  "| `CLAUDE_AI_EFFORT` | `src/selfhost/ai.ts:108` |",
  "| `CLAUDE_AI_MODEL` | `src/selfhost/ai.ts:49` |",
  "| `CLAUDE_AI_TIMEOUT_MS` | `src/selfhost/ai.ts:108` |",
  "| `CODEX_AI_EFFORT` | `src/selfhost/ai.ts:112` |",
  "| `CODEX_AI_MODEL` | `src/selfhost/ai.ts:53` |",
  "| `CODEX_AI_TIMEOUT_MS` | `src/selfhost/ai.ts:112` |",
  "| `CODEX_HOME` | `src/selfhost/ai.ts:274` |",
  "| `CRON_INTERVAL_MS` | `src/server.ts:904` |",
  "| `DATABASE_PATH` | `src/server.ts:250` |",
  "| `DATABASE_URL` | `src/selfhost/preflight.ts:201` |",
  "| `DISCORD_REPO_WEBHOOKS` | `src/services/notify-discord.ts:41` |",
  "| `DISCORD_WEBHOOK_URL` | `src/services/notify-discord.ts:78` |",
  "| `FOREGROUND_LIVENESS_ENABLED` | `src/selfhost/foreground-liveness.ts:41` |",
  "| `GITHUB_APP_ID` | `src/selfhost/orb-collector.ts:59` |",
  "| `GITHUB_APP_PRIVATE_KEY` | `src/selfhost/orb-collector.ts:166` |",
  "| `GITHUB_CACHE_TTL_SECONDS` | `src/server.ts:496` |",
  "| `GITTENSORY_REPO_CONFIG_DIR` | `src/server.ts:284` |",
  "| `GITTENSORY_VERSION` | `src/selfhost/health.ts:29` |",
  "| `HOME` | `src/selfhost/ai.ts:274` |",
  "| `MAINTENANCE_ADMISSION_ENABLED` | `src/selfhost/maintenance-admission.ts:129` |",
  "| `MIGRATIONS_DIR` | `src/server.ts:380` |",
  "| `OBSERVABILITY_SMOKE_POLL_MS` | `scripts/smoke-observability-traces.mjs:8` |",
  "| `OBSERVABILITY_SMOKE_TIMEOUT_MS` | `scripts/smoke-observability-traces.mjs:6` |",
  "| `OLLAMA_AI_API_KEY` | `src/selfhost/ai.ts:829` |",
  "| `OLLAMA_AI_BASE_URL` | `src/selfhost/ai.ts:825` |",
  "| `OLLAMA_AI_MODEL` | `src/selfhost/ai.ts:61` |",
  "| `OPENAI_AI_BASE_URL` | `src/selfhost/ai.ts:827` |",
  "| `OPENAI_AI_MODEL` | `src/selfhost/ai.ts:62` |",
  "| `OPENAI_API_KEY` | `src/selfhost/ai.ts:829` |",
  "| `OPENAI_COMPATIBLE_AI_API_KEY` | `src/selfhost/ai.ts:829` |",
  "| `OPENAI_COMPATIBLE_AI_BASE_URL` | `src/selfhost/ai.ts:828` |",
  "| `OPENAI_COMPATIBLE_AI_MODEL` | `src/selfhost/ai.ts:63` |",
  "| `ORB_AIR_GAP` | `src/selfhost/orb-collector.ts:161` |",
  "| `ORB_ANONYMIZE` | `src/selfhost/orb-collector.ts:174` |",
  "| `ORB_APP_ID` | `src/selfhost/orb-collector.ts:59` |",
  "| `ORB_BROKER_URL` | `src/server.ts:953` |",
  "| `ORB_COLLECTOR_TOKEN` | `src/selfhost/orb-collector.ts:205` |",
  "| `ORB_COLLECTOR_URL` | `src/selfhost/orb-collector.ts:172` |",
  "| `ORB_ENROLLMENT_SECRET` | `src/selfhost/orb-collector.ts:165` |",
  "| `ORB_RELAY_MODE` | `src/server.ts:955` |",
  "| `OTEL_EXPORTER_OTLP_ENDPOINT` | `src/selfhost/otel.ts:47` |",
  "| `OTEL_EXPORTER_OTLP_TRACES_ENDPOINT` | `src/selfhost/otel.ts:45` |",
  "| `OTEL_SERVICE_ENVIRONMENT` | `src/selfhost/otel.ts:60` |",
  "| `OTEL_SERVICE_NAME` | `src/selfhost/otel.ts:59` |",
  "| `OTEL_TRACES_EXPORTER` | `src/selfhost/otel.ts:40` |",
  "| `OTEL_TRACES_SAMPLER` | `src/selfhost/otel.ts:74` |",
  "| `OTEL_TRACES_SAMPLER_ARG` | `src/selfhost/otel.ts:76` |",
  "| `PGVECTOR_ENABLED` | `src/server.ts:230` |",
  "| `PORT` | `src/server.ts:703` |",
  "| `PUBLIC_API_ORIGIN` | `src/selfhost/preflight.ts:192` |",
  "| `QDRANT_API_KEY` | `src/selfhost/qdrant-vectorize.ts:50` |",
  "| `QDRANT_DIM` | `src/selfhost/qdrant-vectorize.ts:71` |",
  "| `QDRANT_URL` | `src/server.ts:515` |",
  "| `QUEUE_BACKGROUND_CONCURRENCY` | `src/selfhost/queue-common.ts:102` |",
  "| `REDIS_URL` | `src/selfhost/preflight.ts:144` |",
  "| `REVIEW_AUDIT_DIR` | `src/server.ts:560` |",
  "| `SELFHOST_BUNDLE_ALL` | `scripts/build-selfhost.mjs:13` |",
  "| `SELFHOST_SERVICE` | `scripts/smoke-observability-traces.mjs:5` |",
  "| `SELFHOST_SETUP_TOKEN` | `src/selfhost/preflight.ts:186` |",
  "| `SENTRY_DSN` | `src/selfhost/sentry.ts:365` |",
  "| `SENTRY_ENVIRONMENT` | `src/selfhost/otel.ts:60` |",
  "| `SENTRY_RELEASE` | `src/selfhost/otel.ts:62` |",
  "| `SENTRY_SERVER_NAME` | `src/selfhost/sentry.ts:383` |",
  "| `SENTRY_TRACES_SAMPLE_RATE` | `src/selfhost/sentry.ts:171` |",
  "| `SETUP_OUTPUT_PATH` | `src/server.ts:820` |",
].join("\n");
