// Generated by scripts/gen-selfhost-env-reference.mjs. Do not edit manually.
export type SelfHostEnvReferenceRow = {
  name: string;
  firstReference: string;
};

export const SELFHOST_ENV_REFERENCE_ROWS: SelfHostEnvReferenceRow[] = [
  {
    name: "AI_COMBINE",
    firstReference: "src/selfhost/ai.ts:848",
  },
  {
    name: "AI_EMBED_API_KEY",
    firstReference: "src/server.ts:416",
  },
  {
    name: "AI_EMBED_BASE_URL",
    firstReference: "src/server.ts:413",
  },
  {
    name: "AI_EMBED_MODEL",
    firstReference: "src/selfhost/ai.ts:744",
  },
  {
    name: "AI_ON_MERGE",
    firstReference: "src/selfhost/ai.ts:850",
  },
  {
    name: "AI_PROVIDER",
    firstReference: "src/selfhost/ai-config.ts:43",
  },
  {
    name: "ANTHROPIC_AI_BASE_URL",
    firstReference: "src/selfhost/ai.ts:748",
  },
  {
    name: "ANTHROPIC_AI_MODEL",
    firstReference: "src/selfhost/ai.ts:57",
  },
  {
    name: "ANTHROPIC_API_KEY",
    firstReference: "src/selfhost/ai.ts:747",
  },
  {
    name: "BACKUP_ACKNOWLEDGED",
    firstReference: "src/server.ts:355",
  },
  {
    name: "BROWSER_WS_ENDPOINT",
    firstReference: "src/selfhost/stubs/puppeteer.ts:11",
  },
  {
    name: "CLAUDE_AI_EFFORT",
    firstReference: "src/selfhost/ai.ts:108",
  },
  {
    name: "CLAUDE_AI_MODEL",
    firstReference: "src/selfhost/ai.ts:49",
  },
  {
    name: "CLAUDE_AI_TIMEOUT_MS",
    firstReference: "src/selfhost/ai.ts:108",
  },
  {
    name: "CODEX_AI_EFFORT",
    firstReference: "src/selfhost/ai.ts:112",
  },
  {
    name: "CODEX_AI_MODEL",
    firstReference: "src/selfhost/ai.ts:53",
  },
  {
    name: "CODEX_AI_TIMEOUT_MS",
    firstReference: "src/selfhost/ai.ts:112",
  },
  {
    name: "CRON_INTERVAL_MS",
    firstReference: "src/server.ts:818",
  },
  {
    name: "DATABASE_PATH",
    firstReference: "src/server.ts:239",
  },
  {
    name: "DATABASE_URL",
    firstReference: "src/selfhost/preflight.ts:140",
  },
  {
    name: "DISCORD_REPO_WEBHOOKS",
    firstReference: "src/selfhost/discord-notify.ts:31",
  },
  {
    name: "DISCORD_WEBHOOK_URL",
    firstReference: "src/selfhost/discord-notify.ts:40",
  },
  {
    name: "GITHUB_APP_ID",
    firstReference: "src/selfhost/orb-collector.ts:59",
  },
  {
    name: "GITHUB_APP_PRIVATE_KEY",
    firstReference: "src/selfhost/orb-collector.ts:166",
  },
  {
    name: "GITHUB_CACHE_TTL_SECONDS",
    firstReference: "src/server.ts:484",
  },
  {
    name: "GITTENSORY_REPO_CONFIG_DIR",
    firstReference: "src/server.ts:272",
  },
  {
    name: "GITTENSORY_VERSION",
    firstReference: "src/selfhost/health.ts:29",
  },
  {
    name: "MIGRATIONS_DIR",
    firstReference: "src/server.ts:368",
  },
  {
    name: "OBSERVABILITY_SMOKE_POLL_MS",
    firstReference: "scripts/smoke-observability-traces.mjs:8",
  },
  {
    name: "OBSERVABILITY_SMOKE_TIMEOUT_MS",
    firstReference: "scripts/smoke-observability-traces.mjs:6",
  },
  {
    name: "OLLAMA_AI_API_KEY",
    firstReference: "src/selfhost/ai.ts:741",
  },
  {
    name: "OLLAMA_AI_BASE_URL",
    firstReference: "src/selfhost/ai.ts:737",
  },
  {
    name: "OLLAMA_AI_MODEL",
    firstReference: "src/selfhost/ai.ts:61",
  },
  {
    name: "OPENAI_AI_BASE_URL",
    firstReference: "src/selfhost/ai.ts:739",
  },
  {
    name: "OPENAI_AI_MODEL",
    firstReference: "src/selfhost/ai.ts:62",
  },
  {
    name: "OPENAI_API_KEY",
    firstReference: "src/selfhost/ai.ts:741",
  },
  {
    name: "OPENAI_COMPATIBLE_AI_API_KEY",
    firstReference: "src/selfhost/ai.ts:741",
  },
  {
    name: "OPENAI_COMPATIBLE_AI_BASE_URL",
    firstReference: "src/selfhost/ai.ts:740",
  },
  {
    name: "OPENAI_COMPATIBLE_AI_MODEL",
    firstReference: "src/selfhost/ai.ts:63",
  },
  {
    name: "ORB_AIR_GAP",
    firstReference: "src/selfhost/orb-collector.ts:161",
  },
  {
    name: "ORB_ANONYMIZE",
    firstReference: "src/selfhost/orb-collector.ts:174",
  },
  {
    name: "ORB_APP_ID",
    firstReference: "src/selfhost/orb-collector.ts:59",
  },
  {
    name: "ORB_BROKER_URL",
    firstReference: "src/server.ts:862",
  },
  {
    name: "ORB_COLLECTOR_TOKEN",
    firstReference: "src/selfhost/orb-collector.ts:205",
  },
  {
    name: "ORB_COLLECTOR_URL",
    firstReference: "src/selfhost/orb-collector.ts:172",
  },
  {
    name: "ORB_ENROLLMENT_SECRET",
    firstReference: "src/selfhost/orb-collector.ts:165",
  },
  {
    name: "ORB_RELAY_MODE",
    firstReference: "src/server.ts:864",
  },
  {
    name: "OTEL_EXPORTER_OTLP_ENDPOINT",
    firstReference: "src/selfhost/otel.ts:47",
  },
  {
    name: "OTEL_EXPORTER_OTLP_TRACES_ENDPOINT",
    firstReference: "src/selfhost/otel.ts:45",
  },
  {
    name: "OTEL_SERVICE_ENVIRONMENT",
    firstReference: "src/selfhost/otel.ts:60",
  },
  {
    name: "OTEL_SERVICE_NAME",
    firstReference: "src/selfhost/otel.ts:59",
  },
  {
    name: "OTEL_TRACES_EXPORTER",
    firstReference: "src/selfhost/otel.ts:40",
  },
  {
    name: "OTEL_TRACES_SAMPLER",
    firstReference: "src/selfhost/otel.ts:74",
  },
  {
    name: "OTEL_TRACES_SAMPLER_ARG",
    firstReference: "src/selfhost/otel.ts:76",
  },
  {
    name: "PGVECTOR_ENABLED",
    firstReference: "src/server.ts:219",
  },
  {
    name: "PORT",
    firstReference: "src/server.ts:622",
  },
  {
    name: "PUBLIC_API_ORIGIN",
    firstReference: "src/selfhost/preflight.ts:131",
  },
  {
    name: "QDRANT_API_KEY",
    firstReference: "src/selfhost/qdrant-vectorize.ts:50",
  },
  {
    name: "QDRANT_DIM",
    firstReference: "src/selfhost/qdrant-vectorize.ts:71",
  },
  {
    name: "QDRANT_URL",
    firstReference: "src/server.ts:503",
  },
  {
    name: "QUEUE_BACKGROUND_CONCURRENCY",
    firstReference: "src/selfhost/queue-common.ts:102",
  },
  {
    name: "REDIS_URL",
    firstReference: "src/selfhost/preflight.ts:83",
  },
  {
    name: "REVIEW_AUDIT_DIR",
    firstReference: "src/server.ts:548",
  },
  {
    name: "SELFHOST_BUNDLE_ALL",
    firstReference: "scripts/build-selfhost.mjs:13",
  },
  {
    name: "SELFHOST_SERVICE",
    firstReference: "scripts/smoke-observability-traces.mjs:5",
  },
  {
    name: "SELFHOST_SETUP_TOKEN",
    firstReference: "src/selfhost/preflight.ts:125",
  },
  {
    name: "SENTRY_DSN",
    firstReference: "src/selfhost/sentry.ts:355",
  },
  {
    name: "SENTRY_ENVIRONMENT",
    firstReference: "src/selfhost/otel.ts:60",
  },
  {
    name: "SENTRY_RELEASE",
    firstReference: "src/selfhost/otel.ts:62",
  },
  {
    name: "SENTRY_SERVER_NAME",
    firstReference: "src/selfhost/sentry.ts:373",
  },
  {
    name: "SENTRY_TRACES_SAMPLE_RATE",
    firstReference: "src/selfhost/sentry.ts:161",
  },
  {
    name: "SETUP_OUTPUT_PATH",
    firstReference: "src/server.ts:739",
  },
];

export const SELFHOST_ENV_REFERENCE_MARKDOWN = [
  "| Name | First reference |",
  "| --- | --- |",
  "| `AI_COMBINE` | `src/selfhost/ai.ts:848` |",
  "| `AI_EMBED_API_KEY` | `src/server.ts:416` |",
  "| `AI_EMBED_BASE_URL` | `src/server.ts:413` |",
  "| `AI_EMBED_MODEL` | `src/selfhost/ai.ts:744` |",
  "| `AI_ON_MERGE` | `src/selfhost/ai.ts:850` |",
  "| `AI_PROVIDER` | `src/selfhost/ai-config.ts:43` |",
  "| `ANTHROPIC_AI_BASE_URL` | `src/selfhost/ai.ts:748` |",
  "| `ANTHROPIC_AI_MODEL` | `src/selfhost/ai.ts:57` |",
  "| `ANTHROPIC_API_KEY` | `src/selfhost/ai.ts:747` |",
  "| `BACKUP_ACKNOWLEDGED` | `src/server.ts:355` |",
  "| `BROWSER_WS_ENDPOINT` | `src/selfhost/stubs/puppeteer.ts:11` |",
  "| `CLAUDE_AI_EFFORT` | `src/selfhost/ai.ts:108` |",
  "| `CLAUDE_AI_MODEL` | `src/selfhost/ai.ts:49` |",
  "| `CLAUDE_AI_TIMEOUT_MS` | `src/selfhost/ai.ts:108` |",
  "| `CODEX_AI_EFFORT` | `src/selfhost/ai.ts:112` |",
  "| `CODEX_AI_MODEL` | `src/selfhost/ai.ts:53` |",
  "| `CODEX_AI_TIMEOUT_MS` | `src/selfhost/ai.ts:112` |",
  "| `CRON_INTERVAL_MS` | `src/server.ts:818` |",
  "| `DATABASE_PATH` | `src/server.ts:239` |",
  "| `DATABASE_URL` | `src/selfhost/preflight.ts:140` |",
  "| `DISCORD_REPO_WEBHOOKS` | `src/selfhost/discord-notify.ts:31` |",
  "| `DISCORD_WEBHOOK_URL` | `src/selfhost/discord-notify.ts:40` |",
  "| `GITHUB_APP_ID` | `src/selfhost/orb-collector.ts:59` |",
  "| `GITHUB_APP_PRIVATE_KEY` | `src/selfhost/orb-collector.ts:166` |",
  "| `GITHUB_CACHE_TTL_SECONDS` | `src/server.ts:484` |",
  "| `GITTENSORY_REPO_CONFIG_DIR` | `src/server.ts:272` |",
  "| `GITTENSORY_VERSION` | `src/selfhost/health.ts:29` |",
  "| `MIGRATIONS_DIR` | `src/server.ts:368` |",
  "| `OBSERVABILITY_SMOKE_POLL_MS` | `scripts/smoke-observability-traces.mjs:8` |",
  "| `OBSERVABILITY_SMOKE_TIMEOUT_MS` | `scripts/smoke-observability-traces.mjs:6` |",
  "| `OLLAMA_AI_API_KEY` | `src/selfhost/ai.ts:741` |",
  "| `OLLAMA_AI_BASE_URL` | `src/selfhost/ai.ts:737` |",
  "| `OLLAMA_AI_MODEL` | `src/selfhost/ai.ts:61` |",
  "| `OPENAI_AI_BASE_URL` | `src/selfhost/ai.ts:739` |",
  "| `OPENAI_AI_MODEL` | `src/selfhost/ai.ts:62` |",
  "| `OPENAI_API_KEY` | `src/selfhost/ai.ts:741` |",
  "| `OPENAI_COMPATIBLE_AI_API_KEY` | `src/selfhost/ai.ts:741` |",
  "| `OPENAI_COMPATIBLE_AI_BASE_URL` | `src/selfhost/ai.ts:740` |",
  "| `OPENAI_COMPATIBLE_AI_MODEL` | `src/selfhost/ai.ts:63` |",
  "| `ORB_AIR_GAP` | `src/selfhost/orb-collector.ts:161` |",
  "| `ORB_ANONYMIZE` | `src/selfhost/orb-collector.ts:174` |",
  "| `ORB_APP_ID` | `src/selfhost/orb-collector.ts:59` |",
  "| `ORB_BROKER_URL` | `src/server.ts:862` |",
  "| `ORB_COLLECTOR_TOKEN` | `src/selfhost/orb-collector.ts:205` |",
  "| `ORB_COLLECTOR_URL` | `src/selfhost/orb-collector.ts:172` |",
  "| `ORB_ENROLLMENT_SECRET` | `src/selfhost/orb-collector.ts:165` |",
  "| `ORB_RELAY_MODE` | `src/server.ts:864` |",
  "| `OTEL_EXPORTER_OTLP_ENDPOINT` | `src/selfhost/otel.ts:47` |",
  "| `OTEL_EXPORTER_OTLP_TRACES_ENDPOINT` | `src/selfhost/otel.ts:45` |",
  "| `OTEL_SERVICE_ENVIRONMENT` | `src/selfhost/otel.ts:60` |",
  "| `OTEL_SERVICE_NAME` | `src/selfhost/otel.ts:59` |",
  "| `OTEL_TRACES_EXPORTER` | `src/selfhost/otel.ts:40` |",
  "| `OTEL_TRACES_SAMPLER` | `src/selfhost/otel.ts:74` |",
  "| `OTEL_TRACES_SAMPLER_ARG` | `src/selfhost/otel.ts:76` |",
  "| `PGVECTOR_ENABLED` | `src/server.ts:219` |",
  "| `PORT` | `src/server.ts:622` |",
  "| `PUBLIC_API_ORIGIN` | `src/selfhost/preflight.ts:131` |",
  "| `QDRANT_API_KEY` | `src/selfhost/qdrant-vectorize.ts:50` |",
  "| `QDRANT_DIM` | `src/selfhost/qdrant-vectorize.ts:71` |",
  "| `QDRANT_URL` | `src/server.ts:503` |",
  "| `QUEUE_BACKGROUND_CONCURRENCY` | `src/selfhost/queue-common.ts:102` |",
  "| `REDIS_URL` | `src/selfhost/preflight.ts:83` |",
  "| `REVIEW_AUDIT_DIR` | `src/server.ts:548` |",
  "| `SELFHOST_BUNDLE_ALL` | `scripts/build-selfhost.mjs:13` |",
  "| `SELFHOST_SERVICE` | `scripts/smoke-observability-traces.mjs:5` |",
  "| `SELFHOST_SETUP_TOKEN` | `src/selfhost/preflight.ts:125` |",
  "| `SENTRY_DSN` | `src/selfhost/sentry.ts:355` |",
  "| `SENTRY_ENVIRONMENT` | `src/selfhost/otel.ts:60` |",
  "| `SENTRY_RELEASE` | `src/selfhost/otel.ts:62` |",
  "| `SENTRY_SERVER_NAME` | `src/selfhost/sentry.ts:373` |",
  "| `SENTRY_TRACES_SAMPLE_RATE` | `src/selfhost/sentry.ts:161` |",
  "| `SETUP_OUTPUT_PATH` | `src/server.ts:739` |",
].join("\n");
