// Generated by scripts/generate-env-reference.mjs (npm run miner:env-reference). Do not edit manually.
export type MinerEnvReferenceRow = {
  name: string;
  firstReference: string;
  defaultValue: string | null;
};

export const AMS_ENV_REFERENCE_ROWS: MinerEnvReferenceRow[] = [
  {
    name: "LOOPOVER_MINER_AMS_COLLECTOR_TOKEN",
    firstReference: "lib/orb-export.js",
    defaultValue: "",
  },
  {
    name: "LOOPOVER_MINER_AMS_COLLECTOR_URL",
    firstReference: "lib/orb-export.js",
    defaultValue: "",
  },
  {
    name: "LOOPOVER_MINER_AMS_OAUTH_CLIENT_ID",
    firstReference: "lib/oauth-device-flow.js",
    defaultValue: "",
  },
  {
    name: "LOOPOVER_MINER_AMS_POLICY_PATH",
    firstReference: "lib/ams-policy.js",
    defaultValue: null,
  },
  {
    name: "LOOPOVER_MINER_ATTEMPT_LOG_DB",
    firstReference: "lib/attempt-log.js",
    defaultValue: null,
  },
  {
    name: "LOOPOVER_MINER_CLAIM_LEDGER_DB",
    firstReference: "lib/claim-ledger.js",
    defaultValue: null,
  },
  {
    name: "LOOPOVER_MINER_CONFIG_DIR",
    firstReference: "lib/deny-hook-synthesis.js",
    defaultValue: "",
  },
  {
    name: "LOOPOVER_MINER_DENY_HOOK_SYNTHESIS_DB",
    firstReference: "lib/deny-hook-synthesis.js",
    defaultValue: "",
  },
  {
    name: "LOOPOVER_MINER_EVENT_LEDGER_DB",
    firstReference: "lib/event-ledger.js",
    defaultValue: null,
  },
  {
    name: "LOOPOVER_MINER_GOVERNOR_LEDGER_DB",
    firstReference: "lib/governor-ledger.js",
    defaultValue: "",
  },
  {
    name: "LOOPOVER_MINER_GOVERNOR_STATE_DB",
    firstReference: "lib/governor-state.js",
    defaultValue: null,
  },
  {
    name: "LOOPOVER_MINER_LOG_LEVEL",
    firstReference: "lib/logger.js",
    defaultValue: "",
  },
  {
    name: "LOOPOVER_MINER_NO_UPDATE_CHECK",
    firstReference: "lib/update-check.js",
    defaultValue: "",
  },
  {
    name: "LOOPOVER_MINER_ORB_EXPORT_DB",
    firstReference: "lib/orb-export.js",
    defaultValue: "",
  },
  {
    name: "LOOPOVER_MINER_PLAN_STORE_DB",
    firstReference: "lib/plan-store.js",
    defaultValue: "",
  },
  {
    name: "LOOPOVER_MINER_POLICY_DOC_CACHE_DB",
    firstReference: "lib/policy-doc-cache.js",
    defaultValue: null,
  },
  {
    name: "LOOPOVER_MINER_POLICY_VERDICT_CACHE_DB",
    firstReference: "lib/policy-verdict-cache.js",
    defaultValue: null,
  },
  {
    name: "LOOPOVER_MINER_PORTFOLIO_QUEUE_DB",
    firstReference: "lib/portfolio-queue.js",
    defaultValue: null,
  },
  {
    name: "LOOPOVER_MINER_PREDICTION_LEDGER_DB",
    firstReference: "lib/prediction-ledger.js",
    defaultValue: "",
  },
  {
    name: "LOOPOVER_MINER_RANKED_CANDIDATES_DB",
    firstReference: "lib/ranked-candidates.js",
    defaultValue: null,
  },
  {
    name: "LOOPOVER_MINER_REPLAY_SNAPSHOT_DB",
    firstReference: "lib/replay-snapshot.js",
    defaultValue: null,
  },
  {
    name: "LOOPOVER_MINER_REPO_CLONE_DIR",
    firstReference: "lib/repo-clone.js",
    defaultValue: "",
  },
  {
    name: "LOOPOVER_MINER_RUN_STATE_DB",
    firstReference: "lib/run-state.js",
    defaultValue: null,
  },
  {
    name: "LOOPOVER_MINER_SENTRY_DSN",
    firstReference: "lib/sentry.js",
    defaultValue: null,
  },
  {
    name: "LOOPOVER_MINER_SENTRY_ENVIRONMENT",
    firstReference: "lib/sentry.js",
    defaultValue: "production",
  },
  {
    name: "LOOPOVER_MINER_VERSION",
    firstReference: "lib/version.js",
    defaultValue: "",
  },
  {
    name: "LOOPOVER_MINER_WORKTREE_ALLOCATOR_DB",
    firstReference: "lib/worktree-allocator.js",
    defaultValue: "",
  },
  {
    name: "LOOPOVER_MINER_WORKTREE_DIR",
    firstReference: "lib/worktree-allocator.js",
    defaultValue: "",
  },
  {
    name: "MINER_CODING_AGENT_PROVIDER",
    firstReference: "lib/laptop-init.js",
    defaultValue: null,
  },
];

export const AMS_ENV_REFERENCE_MARKDOWN = [
  "# loopover-miner environment variable reference",
  "",
  "Generated by `npm run miner:env-reference`. Do not edit manually.",
  "",
  "| Name | First reference | Default |",
  "| --- | --- | --- |",
  '| `LOOPOVER_MINER_AMS_COLLECTOR_TOKEN` | `lib/orb-export.js` | `""` |',
  '| `LOOPOVER_MINER_AMS_COLLECTOR_URL` | `lib/orb-export.js` | `""` |',
  '| `LOOPOVER_MINER_AMS_OAUTH_CLIENT_ID` | `lib/oauth-device-flow.js` | `""` |',
  "| `LOOPOVER_MINER_AMS_POLICY_PATH` | `lib/ams-policy.js` | (none) |",
  "| `LOOPOVER_MINER_ATTEMPT_LOG_DB` | `lib/attempt-log.js` | (none) |",
  "| `LOOPOVER_MINER_CLAIM_LEDGER_DB` | `lib/claim-ledger.js` | (none) |",
  '| `LOOPOVER_MINER_CONFIG_DIR` | `lib/deny-hook-synthesis.js` | `""` |',
  '| `LOOPOVER_MINER_DENY_HOOK_SYNTHESIS_DB` | `lib/deny-hook-synthesis.js` | `""` |',
  "| `LOOPOVER_MINER_EVENT_LEDGER_DB` | `lib/event-ledger.js` | (none) |",
  '| `LOOPOVER_MINER_GOVERNOR_LEDGER_DB` | `lib/governor-ledger.js` | `""` |',
  "| `LOOPOVER_MINER_GOVERNOR_STATE_DB` | `lib/governor-state.js` | (none) |",
  '| `LOOPOVER_MINER_LOG_LEVEL` | `lib/logger.js` | `""` |',
  '| `LOOPOVER_MINER_NO_UPDATE_CHECK` | `lib/update-check.js` | `""` |',
  '| `LOOPOVER_MINER_ORB_EXPORT_DB` | `lib/orb-export.js` | `""` |',
  '| `LOOPOVER_MINER_PLAN_STORE_DB` | `lib/plan-store.js` | `""` |',
  "| `LOOPOVER_MINER_POLICY_DOC_CACHE_DB` | `lib/policy-doc-cache.js` | (none) |",
  "| `LOOPOVER_MINER_POLICY_VERDICT_CACHE_DB` | `lib/policy-verdict-cache.js` | (none) |",
  "| `LOOPOVER_MINER_PORTFOLIO_QUEUE_DB` | `lib/portfolio-queue.js` | (none) |",
  '| `LOOPOVER_MINER_PREDICTION_LEDGER_DB` | `lib/prediction-ledger.js` | `""` |',
  "| `LOOPOVER_MINER_RANKED_CANDIDATES_DB` | `lib/ranked-candidates.js` | (none) |",
  "| `LOOPOVER_MINER_REPLAY_SNAPSHOT_DB` | `lib/replay-snapshot.js` | (none) |",
  '| `LOOPOVER_MINER_REPO_CLONE_DIR` | `lib/repo-clone.js` | `""` |',
  "| `LOOPOVER_MINER_RUN_STATE_DB` | `lib/run-state.js` | (none) |",
  "| `LOOPOVER_MINER_SENTRY_DSN` | `lib/sentry.js` | (none) |",
  '| `LOOPOVER_MINER_SENTRY_ENVIRONMENT` | `lib/sentry.js` | `"production"` |',
  '| `LOOPOVER_MINER_VERSION` | `lib/version.js` | `""` |',
  '| `LOOPOVER_MINER_WORKTREE_ALLOCATOR_DB` | `lib/worktree-allocator.js` | `""` |',
  '| `LOOPOVER_MINER_WORKTREE_DIR` | `lib/worktree-allocator.js` | `""` |',
  "| `MINER_CODING_AGENT_PROVIDER` | `lib/laptop-init.js` | (none) |",
  "",
].join("\n");
